// screens/TermsScreen.js
import React, { useContext } from 'react';
import {
  ScrollView,
  Text,
  StyleSheet,
  useColorScheme,
  Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import i18n from '../utils/i18n';
import { ThemeContext } from '../context/ThemeContext';

export default function TermsScreen() {
  const scheme = useColorScheme(); // 'light' or 'dark'
  const { theme } = useContext(ThemeContext);
  const isDark = (theme || scheme) === 'dark';

  const styles = createStyles(isDark);

  return (
    <SafeAreaView style={styles.safeArea} edges={['top', 'left', 'right', 'bottom']}>
      <ScrollView
        style={styles.container}
        contentInsetAdjustmentBehavior="automatic"
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        <Text style={styles.title}>📄 {i18n.t('terms.title')}</Text>
        <Text style={styles.text}>
          {i18n.t('terms.intro')}

          {'\n\n'}1. {i18n.t('terms.usageTitle')}
          {'\n'}- {i18n.t('terms.usageAge')}
          {'\n'}- {i18n.t('terms.usageDisclaimer')}

          {'\n\n'}2. {i18n.t('terms.paymentTitle')}
          {'\n'}- {i18n.t('terms.paymentServices')}
          {'\n'}- {i18n.t('terms.paymentPricing')}

          {'\n\n'}3. {i18n.t('terms.liabilityTitle')}
          {'\n'}- {i18n.t('terms.liabilityClause')}

          {'\n\n'}4. {i18n.t('terms.contentTitle')}
          {'\n'}- {i18n.t('terms.contentClause')}

          {'\n\n'}5. {i18n.t('terms.changesTitle')}
          {'\n'}- {i18n.t('terms.changesClause')}

          {'\n\n'}{i18n.t('terms.contact')}
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const createStyles = (isDark) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? '#1e1e1e' : '#fff',
    },
    container: {
      flex: 1,
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'android' ? 16 : 0,
    },
    scrollContent: {
      paddingBottom: 40, // 👈 This ensures bottom content is visible
    },
    title: {
      fontSize: 24,
      color: isDark ? '#f8e1c1' : '#1e1e1e',
      fontWeight: 'bold',
      marginBottom: 20,
    },
    text: {
      fontSize: 16,
      color: isDark ? '#fff' : '#1e1e1e',
      lineHeight: 24,
    },
  });



// // screens/TermsScreen.js
// import React from 'react';
// import { ScrollView, Text, StyleSheet } from 'react-native';

// export default function TermsScreen() {
//   return (
//     <ScrollView style={styles.container}>
//       <Text style={styles.title}>📄 Terms of Service</Text>
//       <Text style={styles.text}>
//         By using Tarot Station, you agree to the following:

//         {"\n\n"}1. **Usage**
//         - You must be at least 13 years old to use this app.
//         - All responses are generated by AI and are for entertainment purposes only.

//         {"\n\n"}2. **Payment**
//         - Paid services include chat sessions and bot customization.
//         - Pricing is shown before confirmation.

//         {"\n\n"}3. **Liability**
//         - We are not liable for any actions taken based on AI responses.

//         {"\n\n"}4. **Content**
//         - Do not misuse the app for unlawful purposes.

//         {"\n\n"}5. **Changes**
//         - We reserve the right to update terms at any time.

//         {"\n\n"}Contact us at: support@tarotstation.app
//       </Text>
//     </ScrollView>
//   );
// }

// const styles = StyleSheet.create({
//   container: {
//     flex: 1,
//     backgroundColor: '#1e1e1e',
//     padding: 20,
//   },
//   title: {
//     fontSize: 24,
//     color: '#f8e1c1',
//     fontWeight: 'bold',
//     marginBottom: 20,
//   },
//   text: {
//     fontSize: 16,
//     color: '#fff',
//     lineHeight: 24,
//   },
// });
