// screens/TermsScreen.js
import React from 'react';
import { ScrollView, Text, StyleSheet } from 'react-native';

export default function TermsScreen() {
  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>📄 Terms of Service</Text>
      <Text style={styles.text}>
        By using Tarot Station, you agree to the following:

        {"\n\n"}1. **Usage**
        - You must be at least 13 years old to use this app.
        - All responses are generated by AI and are for entertainment purposes only.

        {"\n\n"}2. **Payment**
        - Paid services include chat sessions and bot customization.
        - Pricing is shown before confirmation.

        {"\n\n"}3. **Liability**
        - We are not liable for any actions taken based on AI responses.

        {"\n\n"}4. **Content**
        - Do not misuse the app for unlawful purposes.

        {"\n\n"}5. **Changes**
        - We reserve the right to update terms at any time.

        {"\n\n"}Contact us at: support@tarotstation.app
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1e1e1e',
    padding: 20,
  },
  title: {
    fontSize: 24,
    color: '#f8e1c1',
    fontWeight: 'bold',
    marginBottom: 20,
  },
  text: {
    fontSize: 16,
    color: '#fff',
    lineHeight: 24,
  },
});
